variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/dafny-linux-mono-build

stages:
  - prebuild
  - build
  - sonar
  - test

build_image:
  stage: prebuild
  image: docker:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile.build
      - .gitlab-ci.yml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $BUILD_IMAGE:latest - < Dockerfile.build
    - docker push $BUILD_IMAGE:latest

build_dafny:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - if [ ! -e boogie ];
        then ln -s /opt/boogie;
      fi;
    - cd dafny/Source
    - nuget restore Dafny.sln
    - msbuild Dafny.sln
  artifacts:
    paths:
      - dafny/Binaries/
      
sonar_test:
  stage: sonar
  image: $BUILD_IMAGE:latest
  script:
    - if [ -n "${SONAR_TOKEN}" ]; then sonar-scanner; fi

build_vscode_extension:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - cd VSCodePlugin
    - npm install
    - npm run vscode:prepublish
  artifacts:
    paths:
      - VSCodePlugin/out/
      
test_mstest:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - "dotnet test dafny/Source/Dafny.sln"
    

test_vscode:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - |
      Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp 2>&1    | grep -v "_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created." &
      xvfb=$!
      for i in $(seq 1 10); do
        echo "Waiting for Xvfb..."
        sleep 1
        xdpyinfo -display ${DISPLAY} >/dev/null 2>&1
        if [ $? -eq 0 ]; then break; fi
        if [ "$i" -gt 9 ]; then echo "Waiting for Xvfb timed out. (Waited for $i seconds)"; exit 255; fi
      done
    - cd VSCodePlugin
    - npm install
    - npm run test
    
test_dafny:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - cd dafny
    - pushd Binaries; ln -s /opt/z3; popd
    - npm install bignumber.js #TODO: Should this be global or in build dependency? Else package.json with fixed versions!
    - cd Test
    - "find . -name '*.dfy' -exec sed -i 's!/optimize !!g' {} +"
    - lit --time-tests -v .
