variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/dafny-linux-mono-build

stages:
  - prebuild
  - build
  - test

build_image:
  stage: prebuild
  image: docker:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile.build
      - .gitlab-ci.yml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $BUILD_IMAGE:latest - < Dockerfile.build
    - docker push $BUILD_IMAGE:latest

build:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - if [ ! -e boogie ];
        then ln -s /opt/boogie;
      fi;
    - cd dafny/Source
    - nuget restore Dafny.sln
    - msbuild -t:restore Dafny.sln
  artifacts:
    paths:
      - dafny/Binaries/

      
test_mstest:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - apt-get install nunit
    - "dotnet test dafny/Source/Dafny.sln"
    

test_vscode:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - apt-get update -y
    - apt-get install -y libgtk-3-0
    - apt-get install -y libxss1
    - apt-get install -y libasound2
    - cd VSCodePlugin
    - npm install
    - npm run test
    
test_dafny:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - pushd Binaries; ln -s /opt/z3; popd
    - npm install bignumber.js #TODO: Should this be global or in build dependency? Else package.json with fixed versions!
    - cd Test
    - "find . -name '*.dfy' -exec sed -i 's!/optimize !!g' {} +"
    - lit --time-tests -v .
