variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/dafny-linux-mono-build

stages:
  - prebuild
  - build
  - test

build_image:
  stage: prebuild
  image: docker:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile.build
      - .gitlab-ci.yml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $BUILD_IMAGE:latest - < Dockerfile.build
    - docker push $BUILD_IMAGE:latest

build:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - cd dafny
    - pushd ../..;
      ls -alh /opt/boogie/; 
      ls -alh /opt/boogie/Binaries/; 
      if [ -e boogie ];
        then rm ./boogie;
      fi;
      pwd; 
      if [ ! -e boogie ];
        then ln -s /opt/boogie;
      fi;
      ls -alh ./boogie;
      popd
    - nuget restore Source/Dafny.sln
    - msbuild Source/Dafny.sln
  artifacts:
    paths:
      - Binaries/

test:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - pushd Binaries; ln -s /opt/z3; popd
    - npm install bignumber.js #TODO: Should this be global or in build dependency? Else package.json with fixed versions!
    - cd Test
    - "find . -name '*.dfy' -exec sed -i 's!/optimize !!g' {} +"
    - lit --time-tests -v .
