variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/dafny-linux-mono-build
  NUnitRunner: NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe
  NUnitFolder: TestBinaries

stages:
  - prebuild
  - build
  - test
  - sonar

build_image:
  stage: prebuild
  image: docker:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile.build
      - .gitlab-ci.yml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $BUILD_IMAGE:latest - < Dockerfile.build
    - docker push $BUILD_IMAGE:latest

build_dafny:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - if [ ! -e boogie ];
        then ln -s /opt/boogie;
      fi;
    - cd dafny/Source
    - nuget restore Dafny.sln
    - msbuild Dafny.sln
  artifacts:
    paths:
      - dafny/Binaries/
      - dafny/Test/TestBinaries/

sonar_test:
  stage: sonar
  image: $BUILD_IMAGE:latest
  only:
    - master@dafny-sa/dafny-server-redesign
  script:
    - sonar-scanner

build_vscode_extension:
  stage: build
  image: $BUILD_IMAGE:latest
  script:
    - cd VSCodePlugin
    - npm install
    - npm run vscode:prepublish
  artifacts:
    paths:
      - VSCodePlugin/out/
      - VSCodePlugin/node_modules/

test_nunit:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - cd dafny/Test/
    - nuget install nunit.consolerunner
    - mono ./$NUnitRunner $NUnitFolder/CompletionHandlerTest.dll
    - mono ./$NUnitRunner $NUnitFolder/VerificationServiceTest.dll
    - mono ./$NUnitRunner $NUnitFolder/CounterExampleTest.dll
  artifacts:
    paths:
      - dafny/Test/TestResult.xml
    reports:
      - dafny/Test/TestResult.xml

test_vscode_xvfb:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - |
      Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp 2>&1    | grep -v "_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created." &
      xvfb=$!
      for i in $(seq 1 10); do
        echo "Waiting for Xvfb..."
        sleep 1
        xdpyinfo -display ${DISPLAY} >/dev/null 2>&1
        if [ $? -eq 0 ]; then break; fi
        if [ "$i" -gt 9 ]; then echo "Waiting for Xvfb timed out. (Waited for $i seconds)"; exit 255; fi
      done
    - cd VSCodePlugin
    - npm install
    - npm run test

test_dafny:
  stage: test
  image: $BUILD_IMAGE:latest
  script:
    - cd dafny
    - pushd Binaries; ln -s /opt/z3; popd
    - npm install bignumber.js #TODO: Should this be global or in build dependency? Else package.json with fixed versions!
    - cd Test
    - "find . -name '*.dfy' -exec sed -i 's!/optimize !!g' {} +"
    - lit --time-tests -v .
