image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  project: "dafny/Source"
  repo: "dafny-server-redesign"
  build_path: "$project/"
  project_path: "dafny/Source/"

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  - "echo \"before script...\""
  - "ls -al"
  - "cd $build_path"
  - "ls -al"
  - "dotnet restore Dafny.sln"

build:
  stage: build
  script:
    - "ls -al"
    - "echo \"building stage...\""
    - "ls -al"
    - "dotnet build Dafny.sln"

test:
  stage: test
  script:
    - dotnet test Dafny.sln